### ISSUE TITLE
Details of Layer-Wise Attention Pooling

### ISSUE THREAD

**Issue by Victoriaheiheihei** [nlpods/LayerAttPooler#1]
Hi,

This is  a very interesting work,but i have some confusions. 
1.What's the shape of three learnable parameters
2. In Equation1 αi is calculated by the sum of (weighted h_i^c and weighted h_j^a),only one layer of h^c is considered when we calculate αi? (shown in the pic below)
![image](https://user-images.githubusercontent.com/55309968/190339927-2dbd0254-fa6c-4f91-ba56-3e8a3183b6e3.png)

**Comment by nlpods** [comment]
Thank you for your interest in our paper.

1. Shape is the same as LM's Hidden Size.
2. Yes, only one layer is considered.
ᐧ

2022년 9월 15일 (목) 오후 4:20, Victoriaheiheihei ***@***.***>님이 작성:

**Comment by Victoriaheiheihei** [comment]
Hello，
sorry to bother again.
There's still something wrong with my experiments.,so I wonder when the code will be public?
I would appreciate it if you could help.

**Comment by nlpods** [comment]
The code will be released after the conference schedule is over.
ᐧ

2022년 9월 20일 (화) 오전 11:35, Victoriaheiheihei ***@***.***>님이
작성:

**Comment by 760bdteam** [comment]
一个类似的问题，参数阿尔法是一个矩阵，还是一个值？

**Comment by 760bdteam** [comment]
或者说alpha的shape是什么。。公式1的连乘是点乘还是叉乘？是否缺少了转置符号？

**Comment by 760bdteam** [comment]
Hello：
A very  attractive paper !
I am trying to reproduce the experiment , but there are some problems bothering me.
1、the shape of αi 
2、Suppose the shape of learnable parameters is [hidden_size,1]. the shape of hidden_states is [batch_size,hidde_size], whether the transpose symbol is missing in the formula If the four variables are multiplied ？
3、Whether the accumulation symbols of Formula 2 and Formula 3 are duplicate？

I would appreciate it if you could reply~
