### ISSUE TITLE
When is open source code?

### ISSUE THREAD

**Issue by daisy-disc** [nlpods/LayerAttPooler#2]
Hello, this is a very interesting job, when will it be open source?

**Comment by nlpods** [comment]
Thank you for your interest in our research. The code will be released
after the conference schedule is over.
ᐧ

2022년 9월 19일 (월) 오후 3:17, Mr_Liu ***@***.***>님이 작성:

**Comment by Victoriaheiheihei** [comment]
Hello，Would you update the code at your convenience?
